// <auto-generated />
namespace humber_http_5226_collaborative_project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class temporarilyRemovedDOBAddressFromIdentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(temporarilyRemovedDOBAddressFromIdentity));
        
        string IMigrationMetadata.Id
        {
            get { return "202404201919315_temporarilyRemovedDOBAddressFromIdentity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
